# Add 'test' label to any change to *.spec.js files within the source dir
test: 
  - src/**/*.spec.js

# Add 'actions' label to any new or updated GitHub action workflow
actions: 
  - .github/workflows/*
